### ISSUE TITLE
Exception fetching ApiOAuth2Application records from DB

### ISSUE THREAD

**Issue by abought** [CenterForOpenScience/cas-overlay#1]
## Summary

CAS is able to fetch data from the database, using a model defined analogously to a pending OSF feature. But when this is used on live data, it raises an exception related to type conversion.

```
 Caused by: 
cas_1      | org.springframework.core.convert.ConversionFailedException: Failed to convert from type java.lang.String to type java.math.BigInteger for value '5581dd549f8b1f9482812e4a'; nested exception is java.lang.NumberFormatException: For input string: "5581dd"
```
## Details

The ODM model in Java assigns field "id" to type `BigInteger`, but Mongo object IDs are alphanumeric.

https://github.com/CenterForOpenScience/cas-overlay/blob/master/cas-server-support-osf/src/main/java/io/cos/cas/services/OpenScienceFrameworkServiceRegistryDao.java#L57

Here is some live data added to the database using the OSF model (appropriately renamed so that the mongo collection and field names align with the java model)

``` javascript
> db.apioauth2application.findOne()
{
    "_id" : "5581dd549f8b1f9482812e4a",
    "create_date" : ISODate("2015-06-17T20:49:24.980Z"),
    "description" : "Who ya gonna call?",
    "_version" : 1,
    "active" : true,
    "client_id" : "f83fd7f407814d96aefb95dd6d03d27e",
    "owner" : "4urxt",
    "client_secret" : "MmE1MGQ3ZmUzNzhhNDJlMWIyZTcyZDU5NjZiZjcwYWU=",
    "callback_url" : "http://goodwill.org",
    "home_url" : "http://tumblr.com",
    "name" : "Application name"
}
```

Here is the relevant ModularODM model definition used to generate the above data:
https://github.com/abought/osf.io/blob/feature/oauth-app-reg-cors/website/project/model.py#L289

This is an expanded version of a verbal report to @icereval 

Blocks implementing token revocation/use in CenterForOpenScience/osf.io/issues/3041

**Comment by icereval** [comment]
Behavior should be corrected by commits fcfc783206fab724d9492dc0728e0f8764bc0366 and 390adb1ca07895e38fd57899d84a0b213b3fc2f1.
