### ISSUE TITLE
Bad authorization grant URL does not result in error message

### ISSUE THREAD

**Issue by abought** [CenterForOpenScience/cas-overlay#2]
## Problem description

When the user visits the authorization grant endpoint (`https://localhost:8443/oauth2/authorize`) for a third-party OAuth2 client application, they must provide a `redirect_uri` that exactly matches the callback registered for that application.

If they do not provide a valid redirect_uri (or a known `client_id`), then the user simply sees a page informing them that they have been logged in. They do not receive an error message, and the callback URL is never notified of the error reason. 
## Possible changes

RFC 6749 provides for `error`, `error_description`, and/or `error_uri` parameters that could be used for this purpose. See example error list in Github's OAuth2 implementation: https://developer.github.com/v3/oauth/#common-errors-for-the-authorization-request

**Comment by abought** [comment]
This problem also occurs when trying to visit the authorization grant screen for an unknown (or deactivated) client ID.

EDIT: To clarify, this is with old CAS. I'll try the modified branch as soon as this PR is clear of functional review.

**Comment by icereval** [comment]
Fixed in: https://github.com/icereval/cas-overlay/commit/bc8b2dd71a47a9bc419af30805222f11042502bd

error_description is now provided for all exceptions
