### ISSUE TITLE
Profile endpoint should not reveal email addresses

### ISSUE THREAD

**Issue by abought** [CenterForOpenScience/cas-overlay#3]
The profile endpoint should not reveal user email addresses.

Below is the current output from a request to `/oauth2/profile`. It was made by an application registered to user 12345, on behalf of user 67890. It reveals the email address of user 67890.

```
{"attributes":
     {"givenName":"Tess","familyName":"Ting","username":"email@nospam.com"},
"id":"67890"}
```

In the future we would like this endpoint to be visible externally (it is not, at present). Link to CenterForOpenScience/osf.io/issues/3323 for tracking purposes.

**Comment by icereval** [comment]
email address removed
