### ISSUE TITLE
OAUTH2 API callback

### ISSUE THREAD

**Issue by chartgerink** [CenterForOpenScience/cas-overlay#6]
When I login via the OAUTH2.0 link (https://test-accounts.osf.io/oauth2/authorize or https://accounts.osf.io/oauth2/authorize) it only states that I successfully logged in, but does not return anything, such that the authentication procedure remains unfinished. 

For example, my R session just keeps waiting for a response. I have tried oauth2/token etc as well, but have not succeeded in getting a callback. I attach some images of my setup, I hope you can help me on this.

![image](https://cloud.githubusercontent.com/assets/2946344/10889968/65f12922-8195-11e5-820e-30c15717755c.png)
![image](https://cloud.githubusercontent.com/assets/2946344/10890013/a34df2dc-8195-11e5-9c5f-56580059ee5b.png)

But remains stuck like this
![image](https://cloud.githubusercontent.com/assets/2946344/10889993/87438642-8195-11e5-80d6-a8d8875325da.png)

The link reads

```
https://test-accounts.osf.io/login?client_id=a796f7d97a5b47ca8d6837152a267641&scope=%2A&redirect_uri=http%3A%2F%2Flocalhost%3A1410&response_type=code&state=p8zgHyxa8A
```

so it does seem like something is going on, but I am just not getting the authorization called back to my machine. My apologies if I am missing something obvious, this is the first API interface I am building and have tried all I can currently think of.

**Comment by lbanner** [comment]
OK @chartgerink ... we'll take a look. @icereval -- when you get a chance, please look at above ^^ issue. Thanks -

**Comment by icereval** [comment]
@chartgerink,

Using a _Personal Access Token_ or _Basic Authorization_ header seem like a better fit for this use case if I'm understanding it correctly.

#### Basic Authorization

This option requires the application ask for the user's credentials for transmission over HTTPS (SSL) as a base64 encoded Authorization header. Credentials are kept in memory and appended to each requests made to the OSF on the user's behalf, no scopes are required for permissions as you are making requests as the user.

#### Personal Access Token (coming soon)

A personal access token can be requested via the API (w/ Basic Authorization) allowing the application to store a personalized token w/ specific scope(s) already authorized. The user only needs to submit their credentials one time when the application is first run and the token is stored to disk for further use.

This option best protects the application and user. The application does not need to store any personal credentials of the user and receives no more control of the user's account than scope(s) configured when the token was setup. Also the user retains the right to revoke authorization of the application specific personal access token at any point.

This feature is nearing production and should be out in the next couple weeks. Currently it is available on staging if you'd like to have a look @ https://staging.osf.io/settings/tokens/ .

If i can answer any questions, please let me know.

Michael

**Comment by chartgerink** [comment]
Thanks! (sorry for the delay)

I got the PAT and am trying to use basic auth with the token. What is the prespecified value for the password when the token is passed as the user? Once I get that it should work; I currently only get 401s.

**Comment by icereval** [comment]
PAT's need to be passed as a Bearer Token in the Authorization Header.

e.g. accessing a private project via the API

`curl -v -X GET -H 'Authorization: Bearer <PAT>'  https://staging-api.osf.io/v2/nodes/8pzyg/`

**Comment by icereval** [comment]
Also, you'll want to account for user's w/ Two Factor authentication enabled on their account. Our implementation is the same as GitHub's w/ a slight change to the name of the header.

Our custom header would be `X-OSF-OTP`.

https://developer.github.com/v3/auth/#working-with-two-factor-authentication

https://github.com/CenterForOpenScience/osf.io/blob/develop/api/base/authentication/drf.py#L80
